/*
* generated by Xtext
*/
package fr.irit.smac.may.speadl;


/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SpeADLStandaloneSetup extends SpeADLStandaloneSetupGenerated{

	public static void doSetup() {
		new SpeADLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

