/*
 * generated by Xtext
 */
package fr.irit.smac.may.speadl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import fr.irit.smac.may.speadl.ui.hover.SpeADLHoverDocumentationProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SpeADLUiModule extends	fr.irit.smac.may.speadl.ui.AbstractSpeADLUiModule {
	public SpeADLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.hover.html.IEObjectHoverDocumentationProvider> bindIEObjectHoverDocumentationProvider() {
		return SpeADLHoverDocumentationProvider.class;
	}
}
