/*
 * generated by Xtext
 */
package fr.irit.smac.may.speadl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.irit.smac.may.speadl.services.SpeADLGrammarAccess;

public class SpeADLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SpeADLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.irit.smac.may.speadl.parser.antlr.internal.InternalSpeADLParser createParser(XtextTokenStream stream) {
		return new fr.irit.smac.may.speadl.parser.antlr.internal.InternalSpeADLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public SpeADLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SpeADLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
